
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.lexico;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int UMINUS = 5;
  public static final int NUMBERDEC = 9;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 6;
  public static final int LPAREN = 7;
  public static final int PERCCOMM = 10;
  public static final int NUMOCTAL = 11;
  public static final int REALNUM = 12;
  public static final int SCIENCNUM = 13;
  public static final int BOOLWORD = 14;
  public static final int INF = 15;  
  public static final int DIV = 16; 
  public static final int AND = 17;  
  public static final int OR = 18;  
  public static final int NOT = 19;  
  public static final int EQUALTO = 20;  
  public static final int GREATERTHAN = 21;  
  public static final int LOWERTHAN = 22;  
  public static final int ASIGN = 23; 
  public static final int SI = 24; 
  public static final int ENTONCES = 25; 
  public static final int SINO = 26; 
  public static final int FINSI = 27; 
  public static final int MIENTRAS = 28; 
  public static final int FINMIENTRAS = 29; 
  public static final int REALTYPE = 30;
  public static final int BOOLEANTYPE = 31; 
  public static final int COMMA = 32; 
  public static final int VARIABLE = 33; 
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "NUMBERDEC",
  "PERCCOMM",
  "NUMOCTAL",
  "REALNUM",
  "SCIENCNUM",
  "BOOLWORD",
  "INF",
  "DIV",
  "AND",
  "OR",
  "NOT",
  "EQUALTO",
  "GREATERTHAN",
  "LOWERTHAN",
  "ASIGN",
  "SI",
  "ENTONCES",
  "SINO",
  "FINSI",
  "MIENTRAS",
  "FINMIENTRAS",
  "REALTYPE",
  "BOOLEANTYPE",
  "COMMA",
  "VARIABLE"
  };
}

